name: publish

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  github-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@vetorial-labs"
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
